# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 273f85a9f05a733c58d767dcd678f8115f67cb4e40e6e2dc9d4b630486e3cf100fc7d13a09bfa7058511064631a9d009e9695ced353196b236ddffcc0242673d

test:
  secret_key_base: 824201599622c6e2548de9c061b29a2d94e2b9104423c4c16364fddcf48f696c25610165e1dde881c7a07b91b560d1e8b128f23927b3ba285d83c38ab36e2ab4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
